// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLQt8jZm_lic1qsChi9wOurjMXgLMK2ew',
    appId: '1:898275021245:web:ac61f1c463327d5af282d4',
    messagingSenderId: '898275021245',
    projectId: 'task-ef61e',
    authDomain: 'task-ef61e.firebaseapp.com',
    databaseURL: 'https://task-ef61e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-ef61e.appspot.com',
    measurementId: 'G-GRTFYD79XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wsFA9Kz3byySpTtUPM1CwANaFtBDc8I',
    appId: '1:898275021245:android:81d4094539c200a0f282d4',
    messagingSenderId: '898275021245',
    projectId: 'task-ef61e',
    databaseURL: 'https://task-ef61e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-ef61e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh493vdAbvsszWp-SD9x866B92K3Gh0Q0',
    appId: '1:898275021245:ios:9ebfdffb98f73177f282d4',
    messagingSenderId: '898275021245',
    projectId: 'task-ef61e',
    databaseURL: 'https://task-ef61e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'task-ef61e.appspot.com',
    iosClientId: '898275021245-t0t1t08700pul53kmlv2a9rdiivrkuub.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
